// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyGEU8n1brGWv_alrFi93oMVH4bVedfCo',
    appId: '1:525799943137:web:4e5715027755055a1480a0',
    messagingSenderId: '525799943137',
    projectId: 'auth-ddefd',
    authDomain: 'auth-ddefd.firebaseapp.com',
    storageBucket: 'auth-ddefd.firebasestorage.app',
    measurementId: 'G-3CDLJBYND9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDdKP6M74xY5B-bTWWiA-8RAJi0wuA_Y',
    appId: '1:525799943137:android:fc147d286ae879d31480a0',
    messagingSenderId: '525799943137',
    projectId: 'auth-ddefd',
    storageBucket: 'auth-ddefd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL61ZQtvPtOYpUgui6XiG-cctG0iuaxgI',
    appId: '1:525799943137:ios:07ed0ab49c81e8961480a0',
    messagingSenderId: '525799943137',
    projectId: 'auth-ddefd',
    storageBucket: 'auth-ddefd.firebasestorage.app',
    iosClientId: '525799943137-knl1m8tjah4r2m40hd66qbceuqdabe56.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobApplyForm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL61ZQtvPtOYpUgui6XiG-cctG0iuaxgI',
    appId: '1:525799943137:ios:07ed0ab49c81e8961480a0',
    messagingSenderId: '525799943137',
    projectId: 'auth-ddefd',
    storageBucket: 'auth-ddefd.firebasestorage.app',
    iosClientId: '525799943137-knl1m8tjah4r2m40hd66qbceuqdabe56.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobApplyForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyGEU8n1brGWv_alrFi93oMVH4bVedfCo',
    appId: '1:525799943137:web:75d9a04d1501d6f31480a0',
    messagingSenderId: '525799943137',
    projectId: 'auth-ddefd',
    authDomain: 'auth-ddefd.firebaseapp.com',
    storageBucket: 'auth-ddefd.firebasestorage.app',
    measurementId: 'G-WW5RTLZ5J9',
  );

}